######################
# project properties #
######################
projectVersion=0.3.0
groupPackage=io.github.astrapi69
projectDescription=Lethenon - a protest chain against the politics of surveillance
projectInceptionYear=2021
projectHolderUsername=astrapi69
projectLeaderName=Asterios Raptis
projectLicenseName=MIT License
projectLicenseUrl=http://www.opensource.org/licenses/mit-license.php
#########################
# dependencies versions #
#########################
mysticCryptVersion=13.5
cryptApiVersion=10.1
cryptDataVersion=13.0
picocliVersion=4.7.7
##############################
# test dependencies versions #
##############################
junitVersion=6.1.3
